# Generated by Django 4.1.3 on 2022-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=250),
        ),
    ]
